### ISSUE TITLE
Setup Search

### ISSUE THREAD

**Issue by classifieds-dev** [rollthecloudinc/verti-go#198]
```bash
#!/bin/bash

# Define variables
STACK_NAME="BaseSearchSystemStack" # Change this to your desired stack name
TEMPLATE_FILE="base_search_system.yaml" # The name of the CloudFormation template file
ENVIRONMENT_NAME="dev" # Replace with your environment name (e.g., dev, prod)
ENVIRONMENT_NAME_CAMEL_CASE="Dev" # Replace with the CamelCase environment name (e.g., Dev, Prod)
VENDOR_SUFFIX="vendor123" # Replace with your vendor suffix
VENDOR_SUFFIX_CAMEL_CASE="Vendor123" # Replace with the CamelCase vendor suffix
USER_POOL_ID="us-east-1_exampleUserPoolId" # Replace with your Cognito User Pool ID
IDENTITY_POOL_ID="us-east-1:exampleIdentityPoolId" # Replace with your Cognito Identity Pool ID

# Check if AWS CLI is installed
if ! command -v aws &> /dev/null; then
    echo "AWS CLI not found. Please install AWS CLI and configure it."
    exit 1
fi

# Package the CloudFormation template (optional, if using SAM or additional transforms)
echo "Packaging CloudFormation template..."
aws cloudformation validate-template --template-body file://"$TEMPLATE_FILE"
if [ $? -ne 0 ]; then
    echo "Template validation failed. Please check your template."
    exit 1
fi

# Deploy the CloudFormation stack
echo "Deploying CloudFormation stack..."
aws cloudformation deploy \
    --stack-name "$STACK_NAME" \
    --template-file "$TEMPLATE_FILE" \
    --parameter-overrides \
        EnvironmentName="$ENVIRONMENT_NAME" \
        EnvironmentNameCamelCase="$ENVIRONMENT_NAME_CAMEL_CASE" \
        VendorSuffix="$VENDOR_SUFFIX" \
        VendorSuffixCamelCase="$VENDOR_SUFFIX_CAMEL_CASE" \
        UserPoolId="$USER_POOL_ID" \
        IdentityPoolId="$IDENTITY_POOL_ID" \
    --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND

# Check the deployment status
if [ $? -eq 0 ]; then
    echo "CloudFormation stack deployed successfully!"
else
    echo "CloudFormation stack deployment failed."
    exit 1
fi
```

**Comment by ng-druid** [comment]
The resource CognitoOpenSearchRole is in a CREATE_FAILED state

This AWS::IAM::Role resource is in a CREATE_FAILED state.

Resource handler returned message: "Invalid principal in policy: "SERVICE":"cognito-identity.amazonaws.com" (Service: Iam, Status Code: 400, Request ID: e5f9db6e-8568-4fc7-9f0d-9cf79c9c8af5) (SDK Attempt Count: 1)" (RequestToken: 35a33adc-0fe7-ed29-990e-7472a2bd3a4d, HandlerErrorCode: InvalidRequest)

**Comment by classifieds-dev** [comment]
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Sample Template: This template sets up the base search system.'

Parameters:
  EnvironmentName:
    Description: The name of the environment (e.g., dev, prod)
    Type: String
  EnvironmentNameCamelCase:
    Description: The name of the environment (e.g., dev, prod) in CamelCase for supporting multiple environments in same account without conflicts.
    Type: String
  VendorSuffix:
    Description: Unique vendor suffix for the bucket.
    Type: String
  VendorSuffixCamelCase:
    Description: Unique vendor suffix in CamelCase for supporting multiple vendors under the same account.
    Type: String
  UserPoolId:
    Description: The ID of the Cognito User Pool
    Type: String
  IdentityPoolId:
    Description: The ID of the Cognito Identity Pool
    Type: String

Resources:
  CognitoOpenSearchRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub 'RtcCognitoOpenSearchRole${EnvironmentNameCamelCase}${VendorSuffixCamelCase}'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "cognito-identity.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub 'RtcCognitoOpenSearchAccess${EnvironmentNameCamelCase}${VendorSuffixCamelCase}'
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "es:ESHttpGet"
                  - "es:ESHttpPut"
                  - "es:ESHttpPost"
                  - "es:ESHttpDelete"
                Resource: !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/rtc-classifieds-${EnvironmentName}-${VendorSuffix}/*'

  MyDomain:
    Type: "AWS::OpenSearchService::Domain"
    Properties:
      DomainName: !Sub 'rtc-classifieds-${EnvironmentName}-${VendorSuffix}'
      EngineVersion: "OpenSearch_2.13"
      ClusterConfig:
        InstanceType: "t3.small.search"
        InstanceCount: 1
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 10
      EncryptionAtRestOptions:
        Enabled: false
      NodeToNodeEncryptionOptions:
        Enabled: false
      DomainEndpointOptions:
        EnforceHTTPS: true
        TLSSecurityPolicy: "Policy-Min-TLS-1-2-2019-07"
      CognitoOptions:
        Enabled: true
        UserPoolId: !Ref UserPoolId
        IdentityPoolId: !Ref IdentityPoolId
        RoleArn: !GetAtt CognitoOpenSearchRole.Arn
```

**Comment by ng-druid** [comment]
The resource MyDomain is in a CREATE_FAILED state

This AWS::OpenSearchService::Domain resource is in a CREATE_FAILED state.

Resource handler returned message: "Invalid request provided: Amazon OpenSearch Service must be allowed to use the passed role (Service: OpenSearch, Status Code: 400, Request ID: 918c2921-ab9d-4a21-a4e6-cd5b86d1fa2e) (SDK Attempt Count: 1)" (RequestToken: 2001ba7d-44bb-3df2-10d4-3ab81e2af6c9, HandlerErrorCode: InvalidRequest)

View the CloudTrail events for this resource

**Comment by classifieds-dev** [comment]
```yaml

            # New permissions for Cognito integration
            - Effect: "Allow"
              Action:
                - "cognito-idp:DescribeUserPool"
                - "cognito-idp:ListUserPoolClients"
                - "cognito-identity:DescribeIdentityPool"
              Resource:
                - !Sub 'arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPoolId}'
                - !Sub 'arn:aws:cognito-identity:${AWS::Region}:${AWS::AccountId}:identitypool/${IdentityPoolId}
```
